#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse


def add(res):
    result = 0
    res = [str(i) for i in res]
    ret = '+'.join(res)
    for i in res:
        result += int(i)
    result = ret + '=' + str(result)
    return result


def print_result(number):
    for i in range(1, number+1):
        if i != 1 and i != number and number > 2:
            print "* " + "  " * (number - 2) + "* "
        else:
            print "* " * number


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-add", "--number",
                        required=False,
                        action="store",
                        type=int,
                        dest="number",
                        nargs="+",
                        help="all number sum"
                        )
    parser.add_argument("-p", "--print",
                        required=False,
                        action="store",
                        type=int,
                        dest="show",
                        help="print *",
                        )

    args = parser.parse_args()
    number = args.number
    show = args.show
    if number:
        res = add(number)
        print "计算结果：%s" % res
    if show:
        print_result(show)


if __name__ == "__main__":
    main()
